open Parser

let pretty_token = function
| IDENT i -> "IDENT(" ^ i ^ ")"
| STRING str -> "STRING(" ^ str ^ ")"
| INT i -> "INT(" ^ Int.to_string i ^ ")" 
| FLOAT f -> "FLOAT"
| LET -> "LET"
| IN -> "IN"
| TRUE -> "TRUE" 
| FALSE -> "FALSE"
| NULL -> "NULL"
| LAMBDA -> "LAMBDA" 
| ARROW -> "ARROW"
| LARROW -> "LARROW"
| DOT -> "DOT"
| COMMA -> "COMMA" 
| SEMI  -> "SEMI"
| COLON -> "COLON"
| LPAREN -> "LPAREN" 
| RPAREN -> "RPAREN" 
| HASHLBRACE -> "HASHLBRACE" 
| LBRACE -> "LBRACE" 
| RBRACE -> "RBRACE" 
| LBRACKET -> "LBRACKET" 
| RBRACKET -> "RBRACKET"
| EQUALS -> "EQUALS" 
| COLONEQUALS -> "COLONEQUALS"
| BANGEQUALS -> "BANGEQUALS" 
| DOUBLEEQUALS -> "DOUBLEEQUALS"
| LT -> "LT"
| GT -> "GT"
| LE -> "LE"
| GE -> "GE"
| PLUS -> "PLUS" 
| MINUS -> "MINUS"
| STAR -> "STAR"
| SLASH -> "SLASH"
| TILDE -> "TILDE"
| DDOT ->  "DDOT"
| OR -> "OR" 
| AND -> "AND" 
| NOT -> "NOT"
| BANG str -> "BANG(" ^ str ^ ")"
| ENVVAR str -> "ENVVAR(" ^ str ^ ")"
| PIPE -> "PIPE"
| IF -> "IF" 
| THEN -> "THEN" 
| ELSE -> "ELSE"
| ASYNC -> "ASYNC" 
| AWAIT -> "AWAIT"
| MATCH -> "MATCH"
| EOF -> "EOF"
| USAGE -> "USAGE"
| DESCRIPTION -> "DESCRIPTION"
| OPTIONS -> "OPTIONS"
| AS -> "AS"
